version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.225.60
      KAFKA_ZOOKEEPER_CONNECT: zookeeper
      KAFKA_CREATE_TOPICS: light:1:1
