apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: overlord
  name: overlord
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: overlord
    spec:
      containers:
      - args:
        - overlord
        env:
        - name: DRUID_MAXNEWSIZE
          value: 100m
        - name: DRUID_NEWSIZE
          value: 100m
        - name: DRUID_XMS
          value: 200m
        - name: DRUID_XMX
          value: 200m
        image: deitch/druid:0.9.2
        name: overlord
        ports:
        - containerPort: 8090
        resources: {}
        volumeMounts:
        - mountPath: /var/druid/segments
          name: druid-vols-claim0
        - mountPath: /var/druid/indexing-logs
          name: druid-vols-claim1
      restartPolicy: Always
      volumes:
      - name: druid-vols-claim0
        persistentVolumeClaim:
          claimName: druid-vols-claim0
      - name: druid-vols-claim1
        persistentVolumeClaim:
          claimName: druid-vols-claim1
status: {}
