kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume-1
  labels:
    type: local
spec:
  storageClassName: fast
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/druid/segments"

