kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume-2
  labels:
    type: local
spec:
  storageClassName: fast
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/druid/indexing-logs"

